spring.application.name=capas

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/gestion_eventos
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
